packages:
  - 'apps/*'
  - 'packages/*'
  - 'seed'
allowBuilds:
  '@firebase/util': true
  argon2: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - html-parse-stringify@4.0.1
  - react-i18next@17.0.11
